version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
  app:
    build: .
    restart: always
    ports:
      - '5001:5001'
    depends_on:
      - db
volumes:
  mongo-data:
